"""ake logo_path nullable in company

Revision ID: 727cd19f9b85
Revises: 7505b8eafa90
Create Date: 2025-10-08 17:17:45.210148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '727cd19f9b85'
down_revision: Union[str, Sequence[str], None] = '7505b8eafa90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'logo_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'logo_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
