"""initial

Revision ID: 9f41d8e03a5c
Revises: 
Create Date: 2025-10-13 00:34:51.869337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f41d8e03a5c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vacancy', 'company', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancy', type_='foreignkey')
    op.drop_column('vacancy', 'company_id')
    # ### end Alembic commands ###
